# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ももつきのーと
subtitle: 'yukiyalien a.k.a. ももつきゆきやが雑多なものを書き残すブログ'
description: 'yukiyalien a.k.a. ももつきゆきやが雑多なものを書き残すブログ'
keywords:
author: yukiyalien
language: ja
timezone: 'Asia/Tokyo'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.yukiya.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

githubEmojis:
  enable: true
  inject: true
  customEmojis:
    nicodic:
      src: /img/nicodic.png
    mastodon:
      src: /img/mastodon.png
    tvchan:
      src: /img/tvchan.png
    youtube:
      src: /img/youtube.png
    niconico:
      src: /img/niconico.png
    nico:
      src: /img/nico.jpg
    namaco:
      src: /img/namaco.png
    github:
      src: /img/github.png
    twitter:
      src: /img/twitter.png
    jr_east:
      src: /img/rail/jr_east.png
    jr:
      src: /img/rail/jr.png
    jre_ja:
      src: /img/rail/jre_ja.png
    jre_jb:
      src: /img/rail/jre_jb.png
    jre_jc:
      src: /img/rail/jre_jc.png
    jre_je:
      src: /img/rail/jre_je.png
    jre_jh:
      src: /img/rail/jre_jh.png
    jre_ji:
      src: /img/rail/jre_ji.png
    jre_jj:
      src: /img/rail/jre_jj.png
    jre_jk:
      src: /img/rail/jre_jk.png
    jre_jl:
      src: /img/rail/jre_jl.png
    jre_jm:
      src: /img/rail/jre_jm.png
    jre_jn:
      src: /img/rail/jre_jn.png
    jre_jo:
      src: /img/rail/jre_jo.png
    jre_js:
      src: /img/rail/jre_js.png
    jre_jt:
      src: /img/rail/jre_jt.png
    jre_ju:
      src: /img/rail/jre_ju.png
    jre_jy:
      src: /img/rail/jre_jy.png
    ks:
      src: /img/rail/ks.png
    mo:
      src: /img/rail/mo.png
    rinkai_line:
      src: /img/rail/rinkai_line.png
    sl:
      src: /img/rail/sl.png
    tm_c:
      src: /img/rail/tm_c.png
    tm_f:
      src: /img/rail/tm_f.png
    tm_g:
      src: /img/rail/tm_g.png
    tm_h:
      src: /img/rail/tm_h.png
    tm_m:
      src: /img/rail/tm_m.png
    tm_mb:
      src: /img/rail/tm_mb.png
    tm_n:
      src: /img/rail/tm_n.png
    tm_t:
      src: /img/rail/tm_t.png
    tm_y:
      src: /img/rail/tm_y.png
    tm_z:
      src: /img/rail/tm_z.png
    toei_a:
      src: /img/rail/toei_a.png
    toei_e:
      src: /img/rail/toei_e.png
    toei_i:
      src: /img/rail/toei_i.png
    toei_s:
      src: /img/rail/toei_s.png
    tokyo_metro:
      src: /img/rail/tokyo_metro.png
    tokyometrogov:
      src: /img/tokyometrogov.png
    tr:
      src: /img/rail/tr.png
    yurikamome:
      src: /img/rail/yurikamome.png