# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ももつきのーと
subtitle: 'yukiyalien a.k.a. ももつきゆきやが雑多なものを書き残すブログ'
description: 'yukiyalien a.k.a. ももつきゆきやが雑多なものを書き残すブログ'
keywords:
author: yukiyalien
language: ja
timezone: 'Asia/Tokyo'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.yukiya.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

githubEmojis:
  enable: true
  inject: true
  customEmojis:
    nicodic: /img/nicodic.png
    mastodon: /img/mastodon.png
    tvchan: /img/tvchan.png
    youtube: /img/youtube.png
    niconico: /img/niconico.png
    nico: /img/nico.jpg
    namaco: /img/namaco.png
    github: /img/github.png
    twitter: /img/twitter.png
    jr_east: /img/rail/jr_east.png
    jr: /img/rail/jr.png
    jre_ja: /img/rail/jre_ja.png
    jre_saikyo: /img/rail/jre_ja.png
    jre_jb: /img/rail/jre_jb.png
    jre_sobu: /img/rail/jre_jb.png
    jre_chuosobu: /img/rail/jre_jb.png
    jre_sobulocal: /img/rail/jre_jb.png
    jre_jc: /img/rail/jre_jc.png
    jre_chuo: /img/rail/jre_jc.png
    jre_chuorapid: /img/rail/jre_jc.png
    jre_ome: /img/rail/jre_jc.png
    jre_itsukaichi: /img/rail/jre_jc.png
    jre_je: /img/rail/jre_je.png
    jre_keiyo: /img/rail/jre_je.png
    jre_jh: /img/rail/jre_jh.png
    jre_yokohama: /img/rail/jre_jh.png
    jre_ji: /img/rail/jre_ji.png
    jre_tsurumi: /img/rail/jre_ji.png
    jre_jj: /img/rail/jre_jj.png
    jre_joban: /img/rail/jre_jj.png
    jre_jobanrapid: /img/rail/jre_jj.png
    jre_jk: /img/rail/jre_jk.png
    jre_keihintohoku: /img/rail/jre_jk.png
    jre_jl: /img/rail/jre_jl.png
    jre_jobanlocal: /img/rail/jre_jl.png
    jre_jm: /img/rail/jre_jm.png
    jre_musashino: /img/rail/jre_jm.png
    jre_jn: /img/rail/jre_jn.png
    jre_nambu: /img/rail/jre_jn.png
    jre_jo: /img/rail/jre_jo.png
    jre_yokosuka: /img/rail/jre_jo.png
    jre_soburapid: /img/rail/jre_jo.png
    jre_js: /img/rail/jre_js.png
    jre_shonanshinjuku: /img/rail/jre_js.png
    jre_jt: /img/rail/jre_jt.png
    jre_tokaido: /img/rail/jre_jt.png
    jre_ito: /img/rail/jre_jt.png
    jre_ju: /img/rail/jre_ju.png
    jre_utsunomiya: /img/rail/jre_ju.png
    jre_takasaki: /img/rail/jre_ju.png
    jre_jy: /img/rail/jre_jy.png
    jre_yamanote: /img/rail/jre_jy.png
    keisei_line: /img/rail/ks.png
    tokyomonorail: /img/rail/mo.png
    rinkai_line: /img/rail/rinkai_line.png
    shinkeisei_line: /img/rail/sl.png
    tm_c: /img/rail/tm_c.png
    tm_f: /img/rail/tm_f.png
    tm_g: /img/rail/tm_g.png
    tm_h: /img/rail/tm_h.png
    tm_m: /img/rail/tm_m.png
    tm_mb: /img/rail/tm_mb.png
    tm_n: /img/rail/tm_n.png
    tm_t: /img/rail/tm_t.png
    tm_y: /img/rail/tm_y.png
    tm_z: /img/rail/tm_z.png
    tokyometro_ginza: /img/rail/tm_g.png
    tokyometro_marunouchi: /img/rail/tm_m.png
    tokyometro_marunouchi_b: /img/rail/tm_mb.png
    tokyometro_hibiya: /img/rail/tm_h.png
    tokyometro_tozai: /img/rail/tm_t.png
    tokyometro_chiyoda: /img/rail/tm_c.png
    tokyometro_yurakucho: /img/rail/tm_y.png
    tokyometro_hanzomon: /img/rail/tm_z.png
    tokyometro_namboku: /img/rail/tm_n.png
    tokyometro_fukutoshin: /img/rail/tm_f.png
    toei_a: /img/rail/toei_a.png
    toei_asakusa: /img/rail/toei_a.png
    toei_e: /img/rail/toei_e.png
    toei_oedo: /img/rail/toei_e.png
    toei_i: /img/rail/toei_i.png
    toei_mita: /img/rail/toei_i.png
    toei_s: /img/rail/toei_s.png
    toei_shinjuku: /img/rail/toei_s.png
    tokyo_sakura_tram: /img/rail/tokyo_sakura_tram.png
    toden_arakawa: /img/rail/tokyo_sakura_tram.png
    nippori_toneri_liner: /img/rail/nipporitoneri.png
    tokyo_metro: /img/rail/tokyo_metro.png
    tokyometrogov: /img/tokyometrogov.png
    toyorapid_line: /img/rail/tr.png
    yurikamome_line: /img/rail/yurikamome.png
    thinking_face:
      src: /img/tw_thinking.png
      codepoints: ["1f914"]
    tw_thinking:
      src: /img/tw_thinking.png
      codepoints: ["1f914"]
    tw_tada:
      src: /img/tw_tada.png
      codepoints: ["1f389"]
    hacker_a: /img/hacker/hacker_a.png
    hacker_b: /img/hacker/hacker_b.png
    hacker_c: /img/hacker/hacker_c.png
    hacker_d: /img/hacker/hacker_d.png
    hacker_e: /img/hacker/hacker_e.png
    hacker_f: /img/hacker/hacker_f.png
    hacker_g: /img/hacker/hacker_g.png
    hacker_h: /img/hacker/hacker_h.png
    hacker_i: /img/hacker/hacker_i.png
    hacker_j: /img/hacker/hacker_j.png
    hacker_k: /img/hacker/hacker_k.png
    hacker_l: /img/hacker/hacker_l.png
    hacker_m: /img/hacker/hacker_m.png
    hacker_n: /img/hacker/hacker_n.png
    hacker_o: /img/hacker/hacker_o.png
    hacker_p: /img/hacker/hacker_p.png
    hacker_q: /img/hacker/hacker_q.png
    hacker_r: /img/hacker/hacker_r.png
    hacker_s: /img/hacker/hacker_s.png
    hacker_t: /img/hacker/hacker_t.png
    hacker_u: /img/hacker/hacker_u.png
    hacker_v: /img/hacker/hacker_v.png
    hacker_w: /img/hacker/hacker_w.png
    hacker_x: /img/hacker/hacker_x.png
    hacker_y: /img/hacker/hacker_y.png
    hacker_z: /img/hacker/hacker_z.png
    keisei_naritaskyaccess: /img/rail/keisei_naritaskyaccess.png
    hokuso_line: /img/rail/hokuso_line.png
    shibayama_railway_line: /img/rail/shibayama_railway_line.png
    nagoyasubway: /img/rail/nagoyasubway.png
    nagoyasubway_higashiyama: /img/rail/nagoyasubway_higashiyama.png
    nagoyasubway_meijo: /img/rail/nagoyasubway_meijo.png
    nagoyasubway_meiko: /img/rail/nagoyasubway_meiko.png
    nagoyasubway_tsurumai: /img/rail/nagoyasubway_tsurumai.png
    nagoyasubway_sakuradori: /img/rail/nagoyasubway_sakuradori.png
    nagoyasubway_kamiiida: /img/rail/nagoyasubway_kamiiida.png
